// ===== 全站内容都在这里：改文字、加项目、换图片只需要改这个文件 =====
// media 里写 images/ 或 videos/ 文件夹里的文件名；.mp4 结尾会自动当成视频
// cover 是左边卡片的小图、首页卡片和 All projects 页用的封面图
// subtitle 是左边卡片和项目页里标题下面那一行小字

window.SITE = {
	name: 'Hazel Tao',
	fullName: 'Honger (Hazel) Tao',
	email: 'heizedesign@gmail.com',
	instagram: 'sol.studioooo',
	now: [
		'MFA Graphic Design, ArtCenter College of Design (May 2027)',
		'BA Design, Washington University in St. Louis (May 2025)',
	],
	updated: '03.20.2026',
	// 左上角时钟显示的城市和时区
	city: 'Los Angeles',
	timezone: 'America/Los_Angeles',
	about: 'Graphic designer working across branding, typography, editorial and print. MFA Graphic Design candidate at ArtCenter College of Design.',
};

window.PROJECTS = [
	{
		slug: 'solserif',
		title: 'Solserif',
		subtitle: 'Expressive serif typeface',
		year: 2026,
		tags: ['Typography'],
		services: ['Typeface Design'],
		format: '',
		cover: 'SU26_solserif_display2.JPG',
		media: [
			'SU26_solserif_display2.JPG', 'SU26_solserif_display3.JPG', 'SU26_solserif_display4.JPG',
			'SU26_solserif_display6.JPG', 'SU26_solserif_display8.JPG', 'SU26_solserif_display9.JPG',
			'SU26_solserif_display5.JPG', 'SU26_solserif_display.JPG',
		],
		text: [
			'Designed in 2026, Solserif is an expressive serif typeface that is warm, friendly, and approachable. It strikes a balance between exceptional legibility and a touch of whimsy. Characterized by soft, organic curves, generous terminals, and unexpected typographic details—such as the distinctive tail of the capital Q, the rounded ear of the lowercase g, and playful serif flourishes.',
		],
	},
	{
		slug: 'sweetness-in-four-seasons',
		title: 'Sweetness in Four Seasons',
		subtitle: 'Limited-edition Risograph calendar',
		year: 2026,
		tags: ['Print', 'Risograph'],
		services: ['Print Design', 'Risograph', 'Calendar'],
		format: '',
		cover: 'Riso_calander_display.jpg',
		media: [
			'IMG_5826.jpg', 'Riso_calander_display.jpg', 'Riso_calander_display2.jpg',
			'Riso_calander_display3.jpg', 'Riso_calander_display4.jpg', 'Riso_calander_display5.jpg',
		],
		text: [
			'Sweetness In Four Season is a limited-edition desktop calendar project exploring the intersections of time, nature, and print craftsmanship. Centered around the concept of "phenological slices of time," the project translates the unique weather patterns, seasonal fruits, and emotional resonance of each month into abstract geometric compositions and distinct RISO spot-color overlays.',
		],
	},
	{
		slug: 'held-still',
		title: 'Held Still',
		subtitle: 'When Time Becomes Visible',
		year: 2026,
		tags: ['Identity', 'Exhibition', 'Motion'],
		services: ['Exhibition Identity', 'Poster', 'Merchandise', 'Motion'],
		format: '',
		cover: 'Heldstill_display3.JPG',
		media: [
			'Heldstill_display3.JPG', 'HeldStill_Ticket.jpg', 'HeldStill_IDCard.jpg', 'HeldStill_BigFlag.jpg',
			'HeldStill_Poster.jpg', 'HeldStill_Flag.jpg', 'Heldstill_display_5.jpg', 'Heldstill_display_3.jpg',
			'Heldstill_display_4.jpg', 'Heldstill_display_6.jpg',
			'HeldStill_FlipThrough-copy.mp4', 'HeldStill_FlipThrough-copy-2.mp4', 'HeldStill_FlipThrough-copy-3.mp4',
			'HeldStill_FlipThrough-copy-4.mp4', 'HeldStill_FlipThrough-copy-5.mp4', 'HeldStill_FlipThrough-copy-6.mp4',
			'SP26_Type4_FIN.jpg', 'HeldStill_Juice.jpg', 'HeldStill_Tote.jpg',
		],
		text: [
			'Held Still: When Time Becomes Visible is a curated exhibition featuring the works of eight artists: Sarah Ball, Eska Marsh, Irving Penn, Paula Siebra, Nicolas Party, Lucas Blalock, Rachel Ruysch, and Michaël Borremans. The collection is united by the enduring genre of still life. My interest in this medium stems from its inherent tension; while these compositions appear frozen to the viewer, they represent a past reality that was once alive. Whether featuring elegant flowers, distorted pears, or a posed model, the objects within these frames were all once part of a living world.',
			'In an era defined by a relentless pace and constant blur, this exhibition serves as a deliberate intervention against the momentum of modern life. It is a quiet invitation to break from daily habits and enter a curated space where the inanimate is finally given the floor to speak. To visually represent this theme, I developed a "super symbol" based on the frame. This motif adapts across various dimensions, including posters, banners, tickets, and merchandise, creating a cohesive visual identity for the show.',
		],
	},
	{
		slug: 'taohe',
		title: 'TAOHE',
		subtitle: 'Yak wool brand, built from the ground up',
		year: 2026,
		tags: ['Identity', 'Packaging', 'Digital', 'Motion'],
		services: ['Brand Strategy', 'Identity System', 'Packaging', 'E-commerce', 'Social'],
		format: '',
		cover: 'Taohe_lookbook_cover_mockup.jpg',
		media: [
			'Taohe_logo_motion_FIN.mp4', 'taohe_social2.jpg', 'Taohe_lookbook_cover_mockup.jpg',
			'Taohe_lookbook_mockup2.jpg', 'Taohe_social_3.jpg', 'Taohe_product_web-copy.jpg',
			'Taohe_pencil_mockup.jpg', 'Taohe_Stationary_Mockup.jpg', 'Taohe_File_envelope.jpg',
			'taohe_boxes.jpg', 'Taohe_tape_mockup.jpg', 'taohe-hm_envelope.jpg', 'taohe-hm_shoppingbag.jpg',
		],
		text: [
			'TAOHE is a brand proposal built from the ground up, rooted in the heritage of my family’s business. Recognizing a significant gap in the U.S. market for premium yak wool, I developed TAOHE to bridge the divide between traditional Tibetan materials and contemporary retail. The project began with deep strategic research—including competitive auditing, brand positioning, and persona development—resulting in a business model centered on 100% yak wool apparel that prioritizes both quality and heritage.',
			'The name TAOHE is a reflection of this personal connection: "Tao" represents my family name, while "He" (和) signifies togetherness in Mandarin. Visually, the brand intentionally breaks away from the delicate, thin-line aesthetics common in luxury cashmere. Instead, the logo and typography embrace a sense of boldness and weight, designed to evoke the warmth and heavy weight of the wool itself. The visual language is defined by juxtaposition, with type treatments inspired by the rugged, natural "ups and downs" of the Tibetan mountain ranges.',
			'To bring the brand to life, I designed a full-scale identity system that spans both digital and physical touchpoints. This includes a complete e-commerce experience with dedicated shop and "about" pages, a curated social media presence, and a detailed packaging suite. The physical collateral—ranging from custom wrapping paper and stationery to hang tags and care instruction cards—ensures a tactile, premium experience for the customer at every stage of the journey.',
		],
		credits: 'Photography Credits: Kin Codel. Creative Director: Zaul Ocana',
	},
	{
		slug: 'arboretum',
		title: 'Arboretum Rebrand Proposal',
		subtitle: 'LA Arboretum & Botanical Garden',
		year: 2025,
		tags: ['Identity', 'Motion', 'Spatial', 'Digital'],
		services: ['Rebrand Proposal', 'Motion', 'Merchandise', 'Spatial', 'Website'],
		format: '',
		cover: 'GS3_FA25_HazelTao_Website4.jpg',
		media: [
			'J-A-Long-LED-Motion.mp4', 'GS3_FA25_-HazelTao_Promo3.mp4', 'GS3_FA25_-HazelTao_Promo2.mp4',
			'GS3_FA25_HazelTao_swag4.jpg', 'GS3_FA25_HazelTao_Website4.jpg', 'GS3_FA25_HazelTao_Website3.jpg',
			'GS3_FA25_HazelTao_Website2.jpg', 'GS3_FA25_HazelTao_Swag2.jpg', 'GS3_FA25_HazelTao_3D-Application1.jpg',
			'GS3_FA25_-HazelTao_Spatial1.jpg', 'Arboretum-Motion-Long-Final.mp4',
			'Screenshot-2026-02-13-at-11.32.12AM.png', 'Screenshot-2026-02-13-at-11.32.01AM.png',
			'Arboretum-Instagram-Mockup.png', 'GS3_FA25_HazelTao_Website6.jpg', 'GS3_FA25_HazelTao_Website5.jpg',
			'GS3_FA25_HazelTao_Website7.jpg', 'GS3_FA25_-HazelTao_Swag1.jpg',
		],
		text: [
			'Proposal for the <a href="https://arboretum.org/">LA Arboretum &amp; Botanical Garden</a>. Stretched typography mimics the rhythm and motion of plant growth. Zoomed-in, close-up imagery creates a more immersive experience-almost letting you smell the freshness right in front of you. Marchandise mockups and spatial for a conceptual collaboration between the LA Arboretum &amp; Botanical Garden and Jennifer Steinkamp.',
		],
	},
	{
		slug: 'edge-of-visibility',
		title: 'Edge of Visibility',
		subtitle: 'Biomorphism pop-up installation',
		year: 2025,
		tags: ['Typography', 'Exhibition', 'Motion', 'Print'],
		services: ['Installation', 'Poster Series', 'Typography', 'Motion'],
		format: '',
		cover: 'EdgeOfVisibility_Mockup_08.png',
		media: [
			'EdgeOfVisibility_Motion_03.mp4', 'EdgeOfVisibility_Mockup_08.png', 'EdgeOfVisibility_Mockup_13.png',
			'EdgeOfVisibility_Mockup_14.png', 'EdgeOfVisibility_Mockup_02.png', 'EdgeOfVisibility_Mockup_01.png',
		],
		text: [
			'Inspired by the screening of <i>Paper and Glue</i> by JR, I explored how art can shape and influence communities. I chose Biomorphism as my focus—a movement emphasizing organic forms, natural growth patterns, and fluid, living aesthetics. I reimagined these principles into a dynamic, immersive pop-up installation that uses typography and visual language to tell a flexible, evolving, and contemporary narrative. The installation features 10 black-and-yellow posters, where typographic forms echo biomorphic shapes, creating a cohesive and adaptable visual system that engages audiences across diverse indoor and outdoor environments.',
		],
	},
	{
		slug: 'utopia',
		title: 'Utopia',
		subtitle: 'Posters for a short film screening',
		year: 2025,
		tags: ['Print'],
		services: ['Poster'],
		format: '24×36”',
		cover: 'Utopia-Poster--for-Print-24x36-01.jpg',
		media: ['Utopia-Poster--for-Print-24x36-01.jpg', 'Utopia-Poster--for-Print-24x36-04.jpg'],
		text: [
			'<i>Utopia</i> was a collaborative short film project. We developed a narrative in which each participant begins in their own personal space: apartment rooms, commuting to work, and so on—and through a series of minor inconveniences, such as missing the bus, getting stuck in traffic, or running late, all characters eventually converge at an elevator, a portal leading to their individual utopias.',
			'Inspired by one particular utopia, filmed at the Spiral Lawn in Los Angeles, I took on the role of designer for the project’s promotional materials. I created a series of posters for the film screening event, translating the film’s dreamlike and euphoria qualities into a visual identity.',
		],
	},
	{
		slug: 'huayings-recipe',
		title: 'Huaying’s Recipe',
		subtitle: 'An accordion-bound calendar',
		year: 2025,
		tags: ['Print', 'Illustration'],
		services: ['Calendar', 'Illustration', 'Print Design'],
		format: '',
		cover: 'FINALp1.jpg',
		media: ['FINALp1.jpg', 'FINALp2-03.png', 'FINALp2-04.png'],
		text: [
			'<i>Huaying’s Recipe</i> is a project that deeply personal tribute to my grandmother and the cherished memories of cooking with her throughout my childhood. Inspired by the calendar she kept on her living room wall, I created a functional and decorative gift that reflects both my love for her and my growth as a designer. Each month features a dish from her recipes, thoughtfully paired with seasonal ingredients or traditional celebrations. The calendar is accordion-bound to enhance display and accessibility, with each month spanning two pages: one showcasing a stylized serving dish illustration, and the other presenting the month’s dates and festivals.',
		],
	},
	{
		slug: 'pied-piper',
		title: 'Pied Piper',
		subtitle: 'Album visual system',
		year: 2024,
		tags: ['Illustration'],
		services: ['Illustration', 'Album Art'],
		format: '',
		cover: 'FINALp1-copy.png',
		media: ['FINALp1-copy.png', 'FINALp3.png', 'FINALp4.jpg', 'FINALp5-copy.png'],
		text: [
			'<i>Pied Piper</i> creates a cohesive visual system for a Red Velvet-inspired album by illustrating a storyline based on key lyrics from five selected songs: “Cosmic,” “Peek-A-Boo,” “Bad Boy,” “Russian Roulette,” and “Feel My Rhythm.” Drawing from a personal concept of two contrasting realms—the gray, numbing Old World and the vibrant, dreamlike New World—the five illustrations visually narrate a transformation. Through symbolic imagery and evolving color palettes, the project shows Red Velvet’s members breaking through the bleakness, seducing the inhabitants into a utopia, and ultimately blending the two worlds into one cohesive vision.',
		],
	},
	{
		slug: 'serenseek',
		title: '‘Serenseek’ 寻真',
		subtitle: 'Teahouse branding',
		year: 2024,
		tags: ['Identity', 'Spatial'],
		services: ['Branding', 'Spatial'],
		format: '',
		cover: 'FINALp1.jpeg',
		media: ['FINALp1.jpeg', 'FINALp4-2.jpg', 'FINALp3.jpg', 'FINALpg5.jpg'],
		text: [
			'<i>‘Serenseek’</i> is a branding project centered around the concept of seeking truth and inner peace. The teahouse offers a tranquil escape from the chaos of city life, inviting visitors to reconnect with themselves and embrace a simpler, more mindful way of living. From the visual identity to the spatial atmosphere, every design element aims to transport guests into a serene, calming environment that nurtures introspection and authenticity.',
		],
	},
	{
		slug: 'wuzhen-theater-festival',
		title: 'Wuzhen Theater Festival',
		subtitle: 'Festival identity redesign',
		year: 2024,
		tags: ['Identity'],
		services: ['Branding', 'Identity System'],
		format: '',
		cover: 'FINALp1-2.jpeg',
		media: ['FINALp1-2.jpeg', 'FINALp3-2.jpg', 'FINALp4.jpeg'],
		text: [
			'This branding project reimagines the visual identity of the Wuzhen Theatre Festival, an international celebration of performance and art held in the rapidly modernizing city of Wuzhen, China. As a native of the region, I was inspired to create a design system that reflects the city’s growing global presence and cultural vibrancy. Moving away from the outdated water-ink textures and muddled logo of past years, my new design embraces bold colors, simplified shapes, and theatrical motifs to capture the festival’s spirit of joy, openness, and creativity.',
		],
	},
	{
		slug: 'find-your-voice',
		title: 'Find Your Voice',
		subtitle: 'Interconnection — editorial typography',
		year: 2024,
		tags: ['Typography', 'Editorial'],
		services: ['Editorial Design', 'Typography'],
		format: '22×11”',
		cover: 'Interconnection.png',
		media: [
			'Interconnection.png',
			'1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_3.jpg', '1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_4.jpg',
			'1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_5.jpg', '1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_6.jpg',
			'1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_7.jpg', '1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_8.jpg',
			'1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_9.jpg', '1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_10.jpg',
			'1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_11.jpg', '1771977244038-086e7f39-f791-4595-a5f4-bbad5819a0a6_12.jpg',
		],
		text: [
			'“Find Your Voice” is an editorial-length typographic design created for my “Typography II” project, titled “Interconnection.” The goal of this project was to establish an organized structure for both written and visual content while allowing room for theme and variation to keep the reader continuously engaged.',
		],
	},
	{
		slug: 'lume',
		title: 'Lume',
		subtitle: 'Identity for pet funeral services',
		year: 2024,
		tags: ['Identity', 'Editorial'],
		services: ['Branding', 'Editorial Design', 'Stationery'],
		format: '',
		cover: 'Lume-Front-Cover-Mockuo.jpg',
		media: [
			'SP25-Lume-Statement-Page.jpg', 'Lume-Busniess-Card-Mockup.jpg', 'Lume-Busniess-Card-Mockup-2.jpg',
			'Lume-Front-Cover-Mockuo.jpg', 'Lume-Inner-Spread-Mockup.jpg', 'Lume-Spread-Mockuop.jpg',
		],
		text: [
			'Lume is a semi-branding project designed to provide thoughtful services for pet funerals. Although I am not a pet owner myself, being surrounded by friends and family who are has made me aware of the need for aftercare services that are visible, dignified, and well-established.',
			'Lume does not aim to depict death in a desperate or hopeless way. Instead, the brand seeks to provide a sense of comfort, reassurance, and reliability. This is primarily achieved through transparency, layered visual elements, and subtle, muted design choices. The goal is to create an identity that feels gentle, trustworthy, and emotionally supportive, offering a meaningful experience for pet owners navigating a difficult time.',
		],
	},
];
